apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: {{ cookiecutter.project_slug | kebabcase }}
  replicas: 2
  template:
    spec:
      containers:
      - name: {{ cookiecutter.project_slug | kebabcase }}
        image: {{ cookiecutter.project_slug }}
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: configmap